.PHONY: build clean

all: build

build: clean
	mkdir build/
	gcc -o build/02 02-circle-trapezium.c
	gcc -o build/03 03-cone-surface.c
	gcc -o build/08 08-bullet-train.c
	gcc -o build/13 13-gotham-city-population.c
	gcc -o build/10 10-deep-earth-temperature.c

clean:
	rm -rf build/
