/*

PROBLEM
  Write a program that takes values for m and n
  as input and displays the values of the Pythagorean triple
  generated by the formulas above

INPUT
  > int m and n, where m > n

OUTPUT
  > phytagorean triple (side1, side2, hypotenuse)

ALGORITHM
  side1 = m^2 - n^2
  side2 = 2mn
  hypotenuse = m^2 + n^2

IMPLEMENTATION
  1. get m and n from input
  2. check whether m > n using if
  3. calculate the value using the provided formula above
  4. print the result out

*/

#include <stdio.h>

int main() {
  int m, n,
      side1, side2, hypotenuse;

  // 1. get m and n from input
  printf("Input the value m and n separated by space (cm) => ");
  scanf("%d %d", &m, &n);

  // 2. check whether m > n using if
  if (m > n) {

    //3. calculate the value using the provided formula above
    side1 = (m*m) - (n*n);
    side2 = 2 * m * n;
    hypotenuse = (m*m) + (n*n);

    // 4. print the result out
    printf("side1: %d cm\nside2: %d cm\nhypotenuse: %d cm\n",
        side1, side2, hypotenuse);
  }
  else {
    printf("m can't be smaller than n!\n");
    return 1;
  }
}
