.PHONY: build clean

all: build

build: clean
	mkdir build/
	gcc -o build/01 01-taxi-fare.c
	gcc -o build/02 02-hydroelectric-dam.c
	gcc -o build/03 03-freezer-temp.c
	gcc -o build/04 04-usd-to-gbp.c
	gcc -o build/05 05-hospital.c
	gcc -o build/06 06-score-prediction.c
	gcc -o build/07 07-btu-efficiency.c
	gcc -o build/08 08-water-saving.c
	gcc -o build/09 09-cutting-grass.c
	gcc -o build/10 10-bisector.c
	gcc -o build/11 11-phytagorean-triplet.c
	gcc -o build/12 12-jet-acceleration.c
	gcc -o build/13 13-student-batch.c

clean:
	rm -rf build/
